### ISSUE TITLE
RINEX v4: Missing GPS CNAV fields

### ISSUE THREAD

**Issue by ljbade** [georust/rinex#146]
I have some time to read through the new `orbits.json` file, and I am comparing it to the modified one I was using from a few months ago and making notes of anything I spot.

GPS CNV2:
- Missing ISCs for L1C:
![image](https://github.com/georust/rinex/assets/1215089/9f23d9c1-3849-4be4-86bd-dc9d2b79992c)
- Might need to add two spares here as last two fields are from the next line, for some reason they don't document that

QZSS CNV2:
- Missing ISCs for L1C:
![image](https://github.com/georust/rinex/assets/1215089/1b0f9f53-8575-42e3-850e-1018236e1dc8)
- Might need to add two spares here as last two fields are from the next line, for some reason they don't document that

BDS CNV1:
- Duplicate keys for `"spare"` - VSCode was highlighting this, should use `spare1`, `spare2`
- Missing field `t_op`: 
![image](https://github.com/georust/rinex/assets/1215089/92e1464a-765e-426e-a0cd-142a1e562d5b)
- `b1c` - it might be clearer that this field has special meaning by adding `integrity`, or `if` to the name
- Missing spare between ISC and TGD:
![image](https://github.com/georust/rinex/assets/1215089/c44b4e93-0ff7-4f0a-91cd-14ca3acc5ac6)

BDS CNV2:
- Duplicate keys for `"spare"` - VSCode was highlighting this, should use `spare1`, `spare2`
- Missing field `t_op`: 
![image](https://github.com/georust/rinex/assets/1215089/92e1464a-765e-426e-a0cd-142a1e562d5b)
- Replace `isc_b1cd` with a spare, then add ISC B2ad between the spare and TGDs:
![image](https://github.com/georust/rinex/assets/1215089/eaa20412-ca35-4199-b25b-ca705705cdfa)
- Rename `b1c` to `b2a_b1c`, possibly adding integrity to name like suggestion above:
![image](https://github.com/georust/rinex/assets/1215089/7b5206f5-7517-4cad-8b4e-49706de154fd)

BDS CNV3:
- Duplicate keys for `"spare"` - VSCode was highlighting this, should use `spare1`, `spare2`
- Missing field `t_op`: 
![image](https://github.com/georust/rinex/assets/1215089/92e1464a-765e-426e-a0cd-142a1e562d5b)
- Delete the `isc_` and `tgd_` values - should go from `sisa1_oc2` to `sismai`:
![image](https://github.com/georust/rinex/assets/1215089/86907d9e-7da4-46a0-bf30-b11e7f7d7c5c)
- Rename `b1c` to `b2b`, possibly adding integrity to name like suggestion above
- Replace `iodc` with `tgd_b2bi`
- Remove the last two spares and `iode`

To help with the test coverage I have attached the IGS RINEX v4 "BRDC" file I was using earlier in the year. This is a useful file as it has every type of NAV data except for GPS CNV2, and BDS CNV3.
[BRD400DLR_S_20230710000_01D_MN.rnx.gz](https://github.com/georust/rinex/files/12462707/BRD400DLR_S_20230710000_01D_MN.rnx.gz)

I will see if there is the missing ones in any newer files.

**Comment by ljbade** [comment]
Looks like latest BRD4 files have BDS CNV3, but still no GPS CNV2:
[BRD400DLR_S_20232400000_01D_MN.rnx.gz](https://github.com/georust/rinex/files/12462761/BRD400DLR_S_20232400000_01D_MN.rnx.gz)

**Comment by gwbres** [comment]
That's awesome @ljbade,


that's also the first file we have with `EOP` frames

![image](https://github.com/georust/rinex/assets/7270467/15b609ba-4351-4a30-b176-5d85fd9958f6)

**Comment by gwbres** [comment]
Ok I'll initiate a draft PR, feel free to join in

I noted several corrections to the JSON descriptor, introduce new test data, etc..
